import './globals.css'
import { Poppins } from '@next/font/google'

const poppins = Poppins({
  weight: ['400', '700'],
  variable: '--font-poppins',
  subsets: ['latin'],
})

export const metadata = {
  title: 'Kanban',
  description: 'Generated by create next app',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="pt-BR">
      <body className={`${poppins.variable} font-sans`}>
          {children}
      </body>
    </html>
  )
}
